# -*- coding: utf-8 -*-
"""board

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t23WE-mXGkXU0SPpnqW_7OlqjSIK56Fc
"""

Row_1 = ["-" , "-" , "-"]
Row_2 = ["-" , "-" , "-"]
Row_3 = ["-" , "-" , "-"]

print(Row_1)
print(Row_2)
print(Row_3)